name: udpierce
version: '0.1.2'
summary: Wrapper which transports UDP packets over multiple TLS sessions
description: >
  Generic network wrapper which transports UDP packets over multiple TLS
  sessions (or plain TCP connections).

confinement: strict
base: core18

parts:
  udpierce:
    plugin: go
    source: .
    build-packages:
      - gcc
    override-build:
      make &&
      cp bin/udpierce "$SNAPCRAFT_PART_INSTALL"
    stage:
      - udpierce

apps:
  udpierce:
    command: udpierce
    plugs:
      - network
      - network-bind
